-- File: dwt.vhd
-- Generated by MyHDL 0.11.51
-- Date:    Tue Dec  2 02:37:09 2025 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity dwt is
    port (
        flgs: in unsigned(2 downto 0);
        upd: in std_logic;
        lft: in unsigned(8 downto 0);
        sam: in unsigned(8 downto 0);
        rht: in unsigned(8 downto 0);
        lift: out signed (9 downto 0);
        done: out std_logic;
        clock: in std_logic
    );
end entity dwt;


architecture MyHDL of dwt is




begin




dwt_rtl: process (clock) is
begin
    if rising_edge(clock) then
        if (upd = '1') then
            done <= '0';
            if (flgs = 7) then
                lift <= (resize(signed(sam), 10) - (shift_right(resize(signed(lft), 10), 1) + shift_right(resize(signed(rht), 10), 1)));
            elsif (flgs = 5) then
                lift <= (resize(signed(sam), 10) + (shift_right(resize(signed(lft), 10), 1) + shift_right(resize(signed(rht), 10), 1)));
            elsif (flgs = 6) then
                lift <= (resize(signed(sam), 10) + shift_right(((resize(signed(lft), 10) + resize(signed(rht), 10)) + 2), 2));
            elsif (flgs = 4) then
                lift <= (resize(signed(sam), 10) - shift_right(((resize(signed(lft), 10) + resize(signed(rht), 10)) + 2), 2));
            end if;
        else
            done <= '1';
        end if;
    end if;
end process dwt_rtl;

end architecture MyHDL;
