// File: dwt.v
// Generated by MyHDL 0.11.51
// Date:    Tue Nov 25 01:44:34 2025 UTC


`timescale 1ns/10ps

module dwt (
    flgs,
    upd,
    lft,
    sam,
    rht,
    lift,
    done,
    clock
);


input [2:0] flgs;
input upd;
input [8:0] lft;
input [8:0] sam;
input [8:0] rht;
output signed [9:0] lift;
reg signed [9:0] lift;
output done;
reg done;
input clock;




always @(posedge clock) begin: dwt_rtl
    if ((upd == 1)) begin
        done <= 0;
        case (flgs)
            'h7: begin
                lift <= ($signed(sam) - ($signed($signed(lft) >>> 1) + $signed($signed(rht) >>> 1)));
            end
            'h5: begin
                lift <= ($signed(sam) + ($signed($signed(lft) >>> 1) + $signed($signed(rht) >>> 1)));
            end
            'h6: begin
                lift <= ($signed(sam) + $signed((($signed(lft) + $signed(rht)) + 2) >>> 2));
            end
            'h4: begin
                lift <= ($signed(sam) - $signed((($signed(lft) + $signed(rht)) + 2) >>> 2));
            end
        endcase
    end
    else begin
        done <= 1;
    end
end

endmodule
