-- File: signed2twoscomplement.vhd
-- Generated by MyHDL 0.11.51
-- Date:    Tue Dec  2 02:37:09 2025 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity signed2twoscomplement is
    port (
        res_o: in signed (9 downto 0);
        z: out unsigned(8 downto 0)
    );
end entity signed2twoscomplement;


architecture MyHDL of signed2twoscomplement is




begin





z <= resize(unsigned(res_o), 9);

end architecture MyHDL;
