// File: signed2twoscomplement.v
// Generated by MyHDL 0.11.51
// Date:    Mon Dec  1 17:02:43 2025 UTC


`timescale 1ns/10ps

module signed2twoscomplement (
    res_o,
    z
);


input signed [9:0] res_o;
output [8:0] z;
wire [8:0] z;





assign z = res_o;

endmodule
